import type { Recipe, Meal, MealType, NutritionLog, ShoppingList, ShoppingListItem, RestaurantOrder, FamilyMembership } from "@shared/schema";

// Mock meal types
export const mockMealTypes: MealType[] = [
  { id: 1, name: "Breakfast", displayOrder: 1 },
  { id: 2, name: "Lunch", displayOrder: 2 },
  { id: 3, name: "Dinner", displayOrder: 3 },
  { id: 4, name: "Snack", displayOrder: 4 },
];

// Mock family members
export const mockFamilyMembers: FamilyMembership[] = [
  {
    id: 1,
    familyId: 1,
    userId: "1",
    role: "admin",
    displayName: "Sarah",
    foodPreferences: ["vegetarian"],
    allergies: ["nuts"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 2,
    familyId: 1,
    userId: "2",
    role: "member",
    displayName: "Mike",
    foodPreferences: ["high-protein"],
    allergies: [],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 3,
    familyId: 1,
    userId: "3",
    role: "member",
    displayName: "Emma",
    foodPreferences: [],
    allergies: ["dairy"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: 4,
    familyId: 1,
    userId: "4",
    role: "member",
    displayName: "Jake",
    foodPreferences: ["no-vegetables"],
    allergies: [],
    createdAt: new Date("2024-01-01"),
  },
];

// Mock recipes
export const mockRecipes: Recipe[] = [
  {
    id: 1,
    familyId: 1,
    name: "Mediterranean Quinoa Bowl",
    description: "A healthy and delicious quinoa bowl with fresh vegetables and feta cheese",
    ingredients: ["quinoa", "cherry tomatoes", "cucumber", "red onion", "feta cheese", "olive oil", "lemon juice", "oregano"],
    instructions: ["Cook quinoa according to package directions", "Chop vegetables", "Mix with olive oil and lemon", "Top with feta and oregano"],
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=300&h=300&fit=crop",
    tags: ["healthy", "vegetarian", "mediterranean"],
    nutritionInfo: { calories: 350, protein: "12", carbs: "45", fat: "14" },
    difficulty: "easy",
    rating: 4.5,
    ratingCount: 8,
    createdBy: "1",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: 2,
    familyId: 1,
    name: "Grilled Chicken Tacos",
    description: "Juicy grilled chicken tacos with fresh toppings",
    ingredients: ["chicken breast", "corn tortillas", "lettuce", "tomatoes", "cheese", "lime", "cilantro", "cumin", "chili powder"],
    instructions: ["Season and grill chicken", "Warm tortillas", "Slice chicken", "Assemble tacos with toppings"],
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=300&h=300&fit=crop",
    tags: ["mexican", "high-protein", "gluten-free"],
    nutritionInfo: { calories: 285, protein: "25", carbs: "18", fat: "12" },
    difficulty: "medium",
    rating: 4.8,
    ratingCount: 12,
    createdBy: "1",
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: 3,
    familyId: 1,
    name: "Creamy Mushroom Pasta",
    description: "Rich and creamy pasta with sautéed mushrooms",
    ingredients: ["pasta", "mushrooms", "heavy cream", "garlic", "parmesan", "butter", "thyme", "white wine"],
    instructions: ["Cook pasta", "Sauté mushrooms and garlic", "Add cream and wine", "Toss with pasta and cheese"],
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc353d946?w=300&h=300&fit=crop",
    tags: ["pasta", "vegetarian", "comfort-food"],
    nutritionInfo: { calories: 420, protein: 14, carbs: 52, fat: 18 },
    difficulty: "medium",
    rating: 4.2,
    ratingCount: 6,
    createdBy: "2",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: 4,
    familyId: 1,
    name: "Berry Smoothie Bowl",
    description: "Healthy breakfast smoothie bowl topped with fresh fruits and granola",
    ingredients: ["frozen berries", "banana", "yogurt", "granola", "honey", "chia seeds", "coconut flakes"],
    instructions: ["Blend frozen berries with banana and yogurt", "Pour into bowl", "Top with granola and fresh toppings"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    imageUrl: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=300&h=300&fit=crop",
    tags: ["healthy", "breakfast", "vegan", "quick"],
    nutritionInfo: { calories: 280, protein: 8, carbs: 48, fat: 6 },
    difficulty: "easy",
    rating: 4.6,
    ratingCount: 10,
    createdBy: "1",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
];

// Mock meals (this week's planned meals)
export const mockMeals: Meal[] = [
  {
    id: 1,
    familyId: 1,
    recipeId: 4,
    mealTypeId: 1,
    scheduledDate: new Date().toISOString().split('T')[0], // Today
    servings: 2,
    notes: "Emma's favorite breakfast",
    status: "planned",
    createdBy: "1",
    createdAt: new Date(),
  },
  {
    id: 2,
    familyId: 1,
    recipeId: 2,
    mealTypeId: 3,
    scheduledDate: new Date().toISOString().split('T')[0], // Today
    servings: 4,
    notes: "Family taco night",
    status: "planned",
    createdBy: "1",
    createdAt: new Date(),
  },
  {
    id: 3,
    familyId: 1,
    recipeId: 1,
    mealTypeId: 2,
    scheduledDate: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    servings: 3,
    notes: "",
    status: "planned",
    createdBy: "1",
    createdAt: new Date(),
  },
];

// Mock nutrition logs
export const mockNutritionLogs: NutritionLog[] = [
  {
    id: 1,
    userId: "1",
    familyId: 1,
    mealTypeId: 1,
    foodName: "Oatmeal with berries",
    calories: 320,
    protein: "8",
    carbs: "58",
    fat: "6",
    fiber: "8",
    sugar: "12",
    sodium: "150",
    loggedDate: new Date().toISOString().split('T')[0],
    createdAt: new Date(),
  },
  {
    id: 2,
    userId: "1",
    familyId: 1,
    mealTypeId: 2,
    foodName: "Grilled chicken salad",
    calories: 380,
    protein: 35,
    carbs: 12,
    fat: 22,
    fiber: 4,
    sugar: 8,
    sodium: 520,
    loggedDate: new Date().toISOString().split('T')[0],
    createdAt: new Date(),
  },
  {
    id: 3,
    userId: "1",
    familyId: 1,
    mealTypeId: 4,
    foodName: "Greek yogurt with almonds",
    calories: 180,
    protein: 15,
    carbs: 12,
    fat: 8,
    fiber: 2,
    sugar: 10,
    sodium: 85,
    loggedDate: new Date().toISOString().split('T')[0],
    createdAt: new Date(),
  },
];

// Mock shopping lists
export const mockShoppingLists: ShoppingList[] = [
  {
    id: 1,
    familyId: 1,
    name: "Weekly Groceries",
    description: "Regular weekly shopping list",
    isActive: true,
    createdBy: "1",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: 2,
    familyId: 1,
    name: "Party Supplies",
    description: "For Emma's birthday party",
    isActive: false,
    createdBy: "1",
    createdAt: new Date("2024-01-28"),
    updatedAt: new Date("2024-01-28"),
  },
];

// Mock shopping list items
export const mockShoppingListItems: ShoppingListItem[] = [
  {
    id: 1,
    shoppingListId: 1,
    name: "Quinoa",
    quantity: "2 lbs",
    category: "Grains",
    isCompleted: false,
    notes: "Organic if available",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: 2,
    shoppingListId: 1,
    name: "Cherry tomatoes",
    quantity: "1 container",
    category: "Produce",
    isCompleted: true,
    notes: "",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: 3,
    shoppingListId: 1,
    name: "Feta cheese",
    quantity: "8 oz",
    category: "Dairy",
    isCompleted: false,
    notes: "",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: 4,
    shoppingListId: 1,
    name: "Chicken breast",
    quantity: "2 lbs",
    category: "Meat",
    isCompleted: false,
    notes: "Free-range",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
  {
    id: 5,
    shoppingListId: 1,
    name: "Corn tortillas",
    quantity: "1 package",
    category: "Bread",
    isCompleted: true,
    notes: "",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-06"),
  },
  {
    id: 6,
    shoppingListId: 1,
    name: "Greek yogurt",
    quantity: "32 oz",
    category: "Dairy",
    isCompleted: false,
    notes: "Plain, low-fat",
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-05"),
  },
];

// Mock restaurant orders
export const mockRestaurantOrders: RestaurantOrder[] = [
  {
    id: 1,
    familyId: 1,
    restaurantName: "Tony's Italian Kitchen",
    orderNumber: "1247",
    totalAmount: 67.85,
    currency: "USD",
    orderDate: new Date("2024-02-03T19:30:00"),
    deliveryAddress: "123 Main St, Anytown, USA",
    status: "delivered",
    cuisine: "Italian",
    items: [
      { name: "Margherita Pizza", quantity: 1, price: 18.99 },
      { name: "Chicken Alfredo", quantity: 1, price: 24.99 },
      { name: "Caesar Salad", quantity: 2, price: 8.99 },
      { name: "Garlic Bread", quantity: 1, price: 6.99 }
    ],
    notes: "Extra cheese on pizza",
    createdBy: "1",
    createdAt: new Date("2024-02-03"),
  },
  {
    id: 2,
    familyId: 1,
    restaurantName: "Jade Garden",
    orderNumber: "8834",
    totalAmount: 52.40,
    currency: "USD",
    orderDate: new Date("2024-01-30T18:15:00"),
    deliveryAddress: "123 Main St, Anytown, USA",
    status: "delivered",
    cuisine: "Chinese",
    items: [
      { name: "Orange Chicken", quantity: 1, price: 15.99 },
      { name: "Beef Broccoli", quantity: 1, price: 16.99 },
      { name: "Fried Rice", quantity: 2, price: 7.99 },
      { name: "Spring Rolls", quantity: 1, price: 5.99 }
    ],
    notes: "",
    createdBy: "2",
    createdAt: new Date("2024-01-30"),
  },
  {
    id: 3,
    familyId: 1,
    restaurantName: "Green Bowl",
    orderNumber: "2156",
    totalAmount: 34.50,
    currency: "USD",
    orderDate: new Date("2024-01-28T12:45:00"),
    deliveryAddress: "123 Main St, Anytown, USA",
    status: "delivered",
    cuisine: "Healthy",
    items: [
      { name: "Quinoa Power Bowl", quantity: 2, price: 13.99 },
      { name: "Green Smoothie", quantity: 2, price: 6.99 }
    ],
    notes: "No nuts in quinoa bowl",
    createdBy: "1",
    createdAt: new Date("2024-01-28"),
  },
];